import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StackQuey from "@/providers/stackQuey";
import { Toaster } from "react-hot-toast";
import StoreProvider from "@/providers/StoreProvider";
import NprogressProvider from "@/providers/Nprogress";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StackQuey>
          <StoreProvider>
            <NprogressProvider>{children}</NprogressProvider>
          </StoreProvider>
          <Toaster position="top-center" />
        </StackQuey>
      </body>
    </html>
  );
}
